#!/bin/sh
set-proxy() {
  export ALL_PROXY=127.0.0.1:1087;
  export http_proxy=http://127.0.0.1:1087;
  export https_proxy=http://127.0.0.1:1087;
}
unset-proxy() {
  unset ALL_PROXY
  unset http_proxy
  unset https_proxy
}

set-proxy
