" neovim config

source ~/.config/vim/vimrc

" When I open a terminal buffer, I want it to feel like I'm in the terminal. I
" don't want to still be in normal mode.
autocmd TermOpen * startinsert


" set verbosefile=~/temp/log/vim.log
" set verbose=1
