#!/bin/bash

echo "agmvim open"
while read line; do

  args=$(echo $line | cut -d ':' -f1 | head -1)
  eval "mvim --remote $args"

  # Notes: macvim --remote not working with line
  # args=$(echo $line | awk -F: '{printf "%s \n+%s\n", $1, $2}' | tr -d '\n')
  # eval "mvim $args"
done
