#!/bin/bash

echo "agnvim remote open"
# Example input data
# t='path/npm.sh:40:  fetchResult'
data=$@

while read line; do
  echo $line | awk -F: '{printf "%s \n+%s\n", $1, $2}' | tr -d '\n' | xargs -I%  nsvc %
done
