#!/bin/sh
# A test script for fzf tmux pop

# # Notes: Can't put FZF_TMUX_OPTS into FZF_DEFAULT_OPTS
# # fzf-tmux is impliment in a bash script
# export FZF_TMUX=1
# export FZF_TMUX_OPTS="-p 85% "
# export TMUX_FZF_OPTIONS=$FZF_TMUX_OPTS

fzf-tmux -p 85% "$@"
