#!/bin/sh
# My wrapper for fzf-tmux, default with pop

IS_FZF_TP="${FZF_TP:-0}"
FZF_TP_OPTS_DEFAULT="-p 85%"
FZF_TP_OPTS_NEW="${FZF_TP_OPTS:-$FZF_TP_OPTS_DEFAULT}"


# FZF_TP_OPTS="-p 60%" nsi

__fzfcmd() {
    echo "fzf-tmux $FZF_TP_OPTS_NEW -- "
}

if [ "$IS_FZF_TP" -eq "1" ]; then
    $(__fzfcmd) "$@"
else
    fzf "$@"
fi
