#!/usr/bin/env bash

read -ra tokens < <(
  kubectl get pods |
    fzf --info=inline --layout=reverse --header-lines=1 \
        --prompt "$(kubectl config current-context | sed 's/-context$//')> " \
        --header $'Press CTRL-O to describle that pod\n\n' \
        --preview-window right,follow \
        --preview 'kubectl describe pods {1}' "$@"
)
[ ${#tokens} -gt 1 ] &&
  kubectl describe pods "${tokens[0]}"

