#!/bin/zsh

NS=$(kcgcn)
CACHE_DIR="$RUNCACHED_CACHE_DIR/$(kube_cache_key $NS)"


rm -rf $CACHE_DIR

runcached_ns kubectl get secret --namespace $NS --kubeconfig $KUBECONFIG > /dev/null &|
runcached_ns kubectl get statefulset --namespace $NS --kubeconfig $KUBECONFIG > /dev/null &|
runcached_ns kubectl get deployment --namespace $NS --kubeconfig $KUBECONFIG > /dev/null &|
runcached_ns kubectl get svc --namespace $NS --kubeconfig $KUBECONFIG > /dev/null &|
