#!/usr/bin/env bash

read -ra tokens < <(
   { cat < "$CURRENT_KUBE_NS_LIST_FILE" & kgns-cached; }  |
    fzf --info=inline --layout=reverse --header-lines=1 \
        --prompt "$(kubectl config current-context | sed 's/-context$//')> " \
        --bind "ctrl-r:reload(cat $CURRENT_KUBE_NS_LIST_FILE)" \
        --preview-window right,follow \
        --preview 'kubectl get pods --namespace {1}' "$@"
)
[ ${#tokens} -gt 1 ] && set-ns "${tokens[0]}"
