#!/bin/zsh

if [[ ! -v ZSH_LOADING_LOG ]] ; then
  ZSH_LOADING_LOG=$HOME/.startup.log
fi

echo "\n[" $$ "]: " "Init logger" >> $ZSH_LOADING_LOG 
echo "[" $$ "]: " $@ >>$ZSH_LOADING_LOG 

function mlog() { 
  echo "[" $$ "]: " $@ >>$ZSH_LOADING_LOG 
}
