#!/bin/zsh
# Namepsace with 20 minutes ttl
POD_ID=$1
RUNCAHED_TTL=${2:-${TTL:-1200}}
NS=${3:-$(kcgcn)}


# Use pod id as cached key
local CACHE_DIR=$RUNCACHED_CACHE_DIR/$(kube_cache_key $POD_ID)

runcached --ignore-pwd --ignore-env --ttl $RUNCAHED_TTL --cache-dir $CACHE_DIR kubectl describe pods --namespace $NS $POD_ID --kubeconfig $KUBECONFIG

# WIP
runcached --ignore-pwd --ignore-env --ttl $RUNCAHED_TTL --cache-dir $CACHE_DIR kubectl describe pods --namespace $NS $POD_ID --kubeconfig $KUBECONFIG > /dev/null &|
