#!/usr/bin/env bash

read -ra tokens < <(
  kubectl get pods --all-namespaces |
    fzf --info=inline --layout=reverse --header-lines=1 \
        --prompt "$(kubectl config current-context | sed 's/-context$//')> " \
        --header $'Press CTRL-O to describle that pod\n\n' \
        --bind ctrl-/:toggle-preview \
        --preview-window right,follow \
        --preview 'kubectl describe pods --namespace {1} {2}' "$@"
)
[ ${#tokens} -gt 1 ] &&
  kubectl describe pods --namespace "${tokens[0]}" "${tokens[1]}" -- bash

