#!/usr/bin/env bash

read -ra tokens < <(

  # kubectl get pods --all-namespaces |
  #   fzf --info=inline --layout=reverse --header-lines=1 \
  #       --prompt "$(kubectl config current-context | sed 's/-context$//')> " \
  #       --header $'Press CTRL-O to describle that pod\n\n' \
  #       --bind ctrl-/:toggle-preview \
  #       --preview-window right,follow \
  #       --preview 'kubectl describe pods --namespace {1} {2}' "$@"

  kubectl get pods --all-namespaces |
      fzf-tmux -p 85% --info=inline --layout=reverse --header-lines=1 \
      --bind "ctrl-r:reload(kgp_cached 0 $(kcgcn))" \
      --prompt "$(kubectl config current-context | sed 's/-context$//') pods> " \
      --preview-window right \
      --preview 'kdp_cached {2} 15 {1}' \
      "$@" \
      | awk '{print $1}'
)
[ ${#tokens} -gt 1 ] &&
  kubectl describe pods --namespace "${tokens[0]}" "${tokens[1]}" -- bash

