#!/bin/zsh

# Create a cache ID as cache diretory based on current context
local RUNCACHED_CACHE_KEY
(
kubectl config current-context
echo "$KUBECONFIG"
echo -E "$@"
) | md5sum | read RUNCACHED_CACHE_KEY RUNCACHED__crap__

echo "$RUNCACHED_CACHE_KEY"
