#!/bin/sh

KUBECONFIG=${2:-$HOME/.kube/config}



echo "----------------------- Secret INFO -------------------------------------------"
echo "-------------------------------------------------------------------------------"

kubectl describe secret $1 --kubeconfig $KUBECONFIG

echo ""
echo "----------------------- Secret Detail -----------------------------------------"
echo "-------------------------------------------------------------------------------"

kubectl get secret $1 --kubeconfig $KUBECONFIG -o json | jq '.data | map_values(@base64d)'


echo ""
echo "-------------------------------------------------------------------------------"
echo "KUBECONFIG: " $KUBECONFIG
echo "NAMESPACE : " $(kcgcn)


# kubectl describe secret {1} --kubeconfig $KUBECONFIG && kubectl get secret {1} --kubeconfig $KUBECONFIG -o json | jq '.data | map_values(@base64d)'
