#!/bin/bash

# Deprecated. I was using CURRENT_KUBE_NS_LIST_FILE as cached file for kgns info. After I start to use
# runcached, this should be deprecated

mlog "[kgns-cached] update ns list cache"
# cat $CURRENT_KUBE_NS_LIST_FILE

nsl=$(kubectl get namespaces --sort-by=.metadata.creationTimestamp)

# echo $nsl >$CURRENT_KUBE_NS_LIST_FILE
echo "$nsl" | awk 'NR == 1; NR > 1 {print $0 | "tac"}' > "$CURRENT_KUBE_NS_LIST_FILE"

mlog "[kgns-cached] update ns list cache complete"
