#!/bin/zsh

KUBECONFIG=${2:-$HOME/.kube/config}


# Method 1
#  "-------------------------------------------------------------------------------"

# echo "------------------------ PODS INFO --------------------------------------------"
# echo "-------------------------------------------------------------------------------"

# kubectl get pods --namespace $1 --kubeconfig $KUBECONFIG

# echo ""
# echo "----------------------- SERVICES INFO -----------------------------------------"
# echo "-------------------------------------------------------------------------------"

# kubectl get svc --namespace $1 --kubeconfig $KUBECONFIG


# echo ""
# echo "-------------------------------------------------------------------------------"
# echo "KUBECONFIG: " $KUBECONFIG


# Method 2
#  "-------------------------------------------------------------------------------"
f1=$(mktemp)
f2=$(mktemp)
f3=$(mktemp)
f4=$(mktemp)

# { kubectl get pods --namespace $1 --kubeconfig $KUBECONFIG } > $f1 &
# kgp_cached use to update cache
{ T_NS=$1 runcached_ns kubectl get pods --namespace $1 --kubeconfig $KUBECONFIG } > $f1 &
P1=$!

{ T_NS=$1 runcached_ns kubectl get svc --namespace $1 --kubeconfig $KUBECONFIG } > $f2 &
P2=$!

{ T_NS=$1 runcached_ns kubectl get deployment --namespace $1 --kubeconfig $KUBECONFIG } > $f3 &
P3=$!

{ T_NS=$1 runcached_ns kubectl get statefulset --namespace $1 --kubeconfig $KUBECONFIG } > $f4 &
P4=$!
echo "-------------------------------------------------------------------------------"
echo "KUBECONFIG: " $KUBECONFIG
echo "DEFAULT NAMESPACE : " $(kcgcn)
echo "PREVIEW NAMESPACE : " $1

echo "------------------------ PODS INFO --------------------------------------------"
echo "-------------------------------------------------------------------------------"

wait $P1 && cat $f1

echo ""
echo "----------------------- SERVICES INFO -----------------------------------------"
echo "-------------------------------------------------------------------------------"


wait $P2 && cat $f2


echo ""
echo "----------------------- DEPLOYMENT INFO -----------------------------------------"
echo "-------------------------------------------------------------------------------"


wait $P3 && cat $f3


echo ""
echo "----------------------- STATEFULSET INFO -----------------------------------------"
echo "-------------------------------------------------------------------------------"


wait $P4 && cat $f4


rm $f1 $f2 $f3 $f4

