#!/bin/sh

function zsh_sample_function {
  local clear list
  zparseopts -E c=clear l=list

  if [[ -n "$clear" ]]; then
    echo "clear"
  elif [[ -n "$list" ]]; then
    echo "list"
  else
    echo "else"
  fi
}


function sample_function() {
    if [ $# -eq 0 ]; then
        echo "Sample function"
        return
    fi
    echo $@
    echo $1
    echo $2
}
